name: CI - Lint and Format

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  lint-and-format:
    runs-on: windows-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        dotnet-version: ['8.0.x']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check formatting
      run: npm run format:check
    
    - name: Run ESLint
      run: npm run lint
    
    - name: Check C# formatting
      run: dotnet format --verify-no-changes
      continue-on-error: true
    
    - name: Build C# projects
      run: dotnet build -p:EnforceCodeStyleInBuild=true
      continue-on-error: true
    
    - name: Upload lint results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: lint-results-${{ matrix.node-version }}
        path: |
          eslint-report.json
          dotnet-format-report.txt
        retention-days: 7